apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-catalog

resources:
  - ../../base/operators.coreos.com/operatorgroups/service-catalog
  - ../../base/operators.coreos.com/subscriptions/crunchy-postgres
